workflows:
  android-native-workflow:
    name: Android Native APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        JAVA_VERSION: "17"
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          if [ -d "app" ]; then echo "sdk.dir=$ANDROID_SDK_ROOT" > app/local.properties; fi
      - name: Upgrade Gradle to 9.3.1
        script: |
          # Homebrew ke zariye Gradle ka latest version system mein install karna
          brew install gradle
          # Check karte hain ke sahi version install ho gayi hai ya nahi
          gradle -v
      - name: Build Android Debug APK
        script: |
          # Upgrade shuda gradle se build run karna
          gradle assembleDebug
    artifacts:
      - "**/build/outputs/apk/debug/*.apk"
    publishing:
      email:
        recipients:
          - temoor007@gmail.com
